services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=emissions_db
    volumes:
      - "./emissions_db:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - "./data_pgadmin:/var/lib/pgadmin:rw"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
      # Pre-configure the server connection:
      - PGADMIN_SERVER_1_NAME=Postgres  # Server name in pgAdmin
      - PGADMIN_SERVER_1_HOST=pgdatabase  # Use the service name as the hostname
      - PGADMIN_SERVER_1_PORT=5432
      - PGADMIN_SERVER_1_USER=root
      - PGADMIN_SERVER_1_PASSWORD=root
      - PGADMIN_SERVER_1_DATABASE=emissions_db
    ports:
      - "8080:80"
    depends_on:  # Ensure pgdatabase starts first
      - pgdatabase


